parts:
  - name: brick1
    type: brick
    brick: 0
    x_offset: 0
    y_offset: -22.5
  - name: motor-left
    type: motor
    x_offset: -60
    y_offset: 0.01
    brick: 0
    port: 'ev3-ports:outA'
  - name: motor-right
    type: motor
    x_offset: 60
    y_offset: 0.01
    brick: 0
    port: 'ev3-ports:outD'
  - name: color-sensor-center
    type: color_sensor
    x_offset: 0
    y_offset: 81
    brick: 0
    port: 'ev3-ports:in2'
  - name: touch-sensor-left
    type: touch_sensor
    side: left
    x_offset: -75
    y_offset: 102
    brick: 0
    port: 'ev3-ports:in1'
  - name: touch-sensor-right
    type: touch_sensor
    side: right
    x_offset: 75
    y_offset: 102
    brick: 0
    port: 'ev3-ports:in4'
  - name: ultrasonic-sensor-front
    type: ultrasonic_sensor
    x_offset: 0
    y_offset: -91.5
    brick: 0
    port: 'ev3-ports:in3'