robots:
  - name: robot0
    center_x: 180
    center_y: 200
    orientation: 0
    type: 'large_robot'

board_height: 1273
board_width: 1273
board_color: 59, 60, 54
obstacles:
  - name: 'border'
    outer_spacing: 23
    depth: 15
    color: 255, 255, 255
    type: 'border'

  - name: 'lake_blue'
    border_width: 29
    inner_radius: 38
    color: 58, 166, 221
    x: 137
    y: 922
    type: 'lake'

  - name: 'lake_green'
    border_width: 29
    inner_radius: 38
    color: 252, 227, 3
    x: 1052
    y: 567
    type: 'lake'

  - name: 'lake_red'
    border_width: 29
    inner_radius: 38
    color: 201, 45, 57
    x: 397
    y: 232
    type: 'lake'

  - name: 'rock1'
    x: 825
    y: 1050
    width: 150
    height: 120
    color: 139, 139, 139
    angle: 10
    type: 'rock'
    movable: False

  - name: 'rock2'
    x: 975
    y: 275
    width: 200
    height: 90
    color: 179, 179, 179
    angle: 130
    type: 'rock'
    movable: True