name: bash on windows

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: bash
        shell: bash
        run: ls -la && pwd && which bash && bash --version
