name: TestBinaryInstall

on: workflow_dispatch 

jobs:
  test_binary_install:
    name: Test binary install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.10, 3.12]
    # strategy:
    #   matrix:
    #     #os: [ubuntu-latest]
    #     # manylinux wheel had problem with absolute path to alsa system, so better to build from source which always works
    #     os: [windows-latest, macos-13, macos-14]
    #     # macos-13: macos intel
    #     # macos-14: macos M1    Note: macos-latest=macos-14
    #     # see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        

    steps:
      - uses: actions/checkout@v4

      - name: test binary install
        shell: bash
        run: |
          pip install '--only-binary=:all:'  --no-cache-dir  'ev3dev2simulator==2.0.10'  >& out.txt 
          #mv  out.txt log-${{ matrix.os }}-py${{ matrix.python-version }}.exit$?.txt     

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: log-${{ matrix.os }}-py${{ matrix.python-version }}
          path: log-${{ matrix.os }}-py${{ matrix.python-version }}.txt


  upload:
    runs-on: ubuntu-latest   
    needs: test_binary_install
    
    steps: 
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: wheel-*
        path: logs/
        merge-multiple: true
        
    - name: Upload wheels in single artifact
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs/*.whl

    - uses: geekyeggo/delete-artifact@v5
      with:
          name: log-*
    
